Update date format
webuild-community/federated-blog pull request #34
Opened 2021-06-26 09:31 UTC by monodyle

Changed in this MR:
- Added date format util
- Format date to day/month/year instead of month/day/year (Vietnamese friendly)

2021-06-26 09:56 UTC, ldhnam approved these changes

2021-06-26 13:44 UTC, lqt93 approved these changes
LGTM

2021-06-26 21:04 UTC, huytd commented on utils/date.ts
> +  new Intl.DateTimeFormat('en-GB').format(new Date(date));
Let use the browser's locale here instead of a hard coded UK region

2021-06-26 21:05 UTC, huytd commented on utils/date.ts
> +  new Intl.DateTimeFormat('en-GB').format(new Date(date));
Also, make it configurable, should be another param of the `formatDate` function just in case.

2021-06-26 23:20 UTC, huytd requested changes
Please add the parameter for locale and set it default to the browser's locale.

2021-06-27 06:20 UTC, monodyle commented
Okay, I will set it to the browser's locate as default. But it was the browser's language FYI:

![image](https://user-images.githubusercontent.com/30283022/123534839-44fe4b80-d74a-11eb-8dce-91de9ca40463.png)

2021-06-27 06:28 UTC, monodyle commented
I have added `options` params, which can output different formats.

Example:

```
formatDate(formatDate(Date.now(), "vi-VN", {
  dateStyle: "long"
})
```

will output: `27 tháng 6, 2021` or `June 27, 2021` in `en-US` locate case.

2021-06-27 17:40 UTC, huytd approved these changes

2021-06-27 17:40 UTC, merged