[WIP] Implement author's profile page
webuild-community/federated-blog pull request #70
Opened 2021-07-07 23:37 UTC by huytd

Squash before merging.

Fixed #42 

![image](https://user-images.githubusercontent.com/613943/124841141-709ae600-df41-11eb-9536-adb24351cadd.png)

Test build: https://vercel.com/kingbazoka/webuild-blog/H7DAsLnhZ22renn6s7vnXc5RHaBx

2021-07-08 09:40 UTC, lqt93 requested changes

2021-07-08 09:40 UTC, lqt93 commented on pages/author/[host].tsx
> +    const author = channelsData.channels[authorId];
Duplicated with line 30

2021-07-08 17:28 UTC, huytd commented on pages/author/[host].tsx
> +    const author = channelsData.channels[authorId];
bingo 😆

2021-07-09 03:40 UTC, lqt93 reviewed
Instead of the console.log, the others LGTM. 💯

2021-07-09 03:40 UTC, lqt93 commented on pages/read/[encoded].tsx
> +    console.error(error);
Should we log the error :-?

2021-07-09 04:47 UTC, lqt93 approved these changes

2021-07-10 23:20 UTC, huytd commented on pages/read/[encoded].tsx
> +    console.error(error);
Yes, for better debug

2021-07-10 23:20 UTC, merged